In [1]:
from collections import namedtuple
import numpy as np

In [2]:
# Define a named tuple to hold data about agents moving within a graph.
AgentPosition = namedtuple('AgentPosition', [
    # The node from which the agent departed or is currently located.
    'node_from',
    # The node to which the agent is going, or -1 if the agent is standing at 'node_from'.
    'node_to',
    # The remaining distance to reach the 'node_to'.
    'distance_to_go'
])

In [3]:
x = [ AgentPosition(i, -1, 0) for i in range(10) ]

In [4]:
x

[AgentPosition(node_from=0, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=1, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=2, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=3, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=4, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=5, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=6, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=7, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=8, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=9, node_to=-1, distance_to_go=0)]

In [5]:
list(x)

[AgentPosition(node_from=0, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=1, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=2, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=3, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=4, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=5, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=6, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=7, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=8, node_to=-1, distance_to_go=0),
 AgentPosition(node_from=9, node_to=-1, distance_to_go=0)]

In [6]:
obs = np.zeros(shape=(10,3))

In [7]:
np.asarray(x)

array([[ 0, -1,  0],
       [ 1, -1,  0],
       [ 2, -1,  0],
       [ 3, -1,  0],
       [ 4, -1,  0],
       [ 5, -1,  0],
       [ 6, -1,  0],
       [ 7, -1,  0],
       [ 8, -1,  0],
       [ 9, -1,  0]])

In [8]:
obs

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# não pode!
#x[0].node_from = 10

In [10]:
x[0]._replace(node_from=10)

AgentPosition(node_from=10, node_to=-1, distance_to_go=0)

In [11]:
from patrolling_env.graph_env_weighted import WeightedGraphPatrolEnv
from patrolling_agents.graph_env_wrapper_weighted import NeighborhoodFeaturesWrapper

In [12]:
from numpy.random import choice

In [20]:
env = WeightedGraphPatrolEnv('map_a.adj', 2)
env = NeighborhoodFeaturesWrapper(env, 'npic', normalization='no')

In [21]:
env.reset(initial_positions=[10,20], keep_stats=True)

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.]]])

In [22]:
#choice(4, size=(2,), replace=True)

In [23]:
for step in range(5):
    print(f"STEP {step}")
    action = choice(4, size=(2,), replace=True) #env.action_space.sample()
    state, reward, done, _ = env.step(action)
    display(env.last_obs)
    display(state)
    

STEP 0


array([[10, 31,  5],
       [20, 28,  2]])

tensor([[[1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.]]])

STEP 1


array([[10, 10,  0],
       [20, 28,  1]])

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [2., 2., 2., 2., 2., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.]],

        [[1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [2., 2., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.]]])

STEP 2


array([[10, 43, 13],
       [28, 28,  0]])

tensor([[[2., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 3., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.]],

        [[0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [3., 3., 3., 3., 3., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.]]])

STEP 3


array([[10, 43, 12],
       [28, 27, 10]])

tensor([[[2., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [2., 4., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 4., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.]]])

STEP 4


array([[10, 43, 11],
       [28, 27,  9]])

tensor([[[2., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [3., 5., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [2., 5., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0., 0., 0.]]])

In [24]:
env.graph.get_weight(10,40)

11

In [25]:
env.graph.get_weight(20,8)

4

In [26]:
env.get_stats()

[(AgentPosition(node_from=10, node_to=10, distance_to_go=0),
  AgentPosition(node_from=20, node_to=20, distance_to_go=0)),
 (AgentPosition(node_from=10, node_to=31, distance_to_go=5),
  AgentPosition(node_from=20, node_to=28, distance_to_go=2)),
 (AgentPosition(node_from=10, node_to=10, distance_to_go=0),
  AgentPosition(node_from=20, node_to=28, distance_to_go=1)),
 (AgentPosition(node_from=10, node_to=43, distance_to_go=13),
  AgentPosition(node_from=28, node_to=28, distance_to_go=0)),
 (AgentPosition(node_from=10, node_to=43, distance_to_go=12),
  AgentPosition(node_from=28, node_to=27, distance_to_go=10)),
 (AgentPosition(node_from=10, node_to=43, distance_to_go=11),
  AgentPosition(node_from=28, node_to=27, distance_to_go=9))]